# -*- coding: utf-8 -*-
"""03 Law of Large Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1od4DqeWTU_K1B1ESpBPmTMeUb3364SVW

#  Law of Large Numbers

https://colab.research.google.com/
"""

import numpy

list_of_coin_flips = numpy.array([2, 4, 6, 8, 12, 14, 16, 18, 20, 32, 64,
                                  128, 256, 512, 1024, 2048])

heads = [numpy.random.binomial(n, 0.5) for n in list_of_coin_flips]

heads_ratio = heads / list_of_coin_flips 

print(heads_ratio)

import matplotlib.pyplot as pyplot 

pyplot.figure(figsize = (10, 5))

pyplot.rcParams.update({'font.size': 18})

pyplot.scatter(list_of_coin_flips, heads_ratio)

pyplot.ylabel('Ratio of Heads')

pyplot.xlabel('# Coin Flips ')

pyplot.axhline(0.5)