# -*- coding: utf-8 -*-
"""04 Calculate Center of Distribution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxxmXYV1Il4PrDiA-74h83A135UJ4407

#  Calculate Center of Distribution

https://colab.research.google.com
"""

import numpy

number_of_flips_per_experiment = 1

probability_of_heads = 0.5

total_experiments = 1000

flipped_heads = numpy.random.binomial(number_of_flips_per_experiment,
                                      probability_of_heads,
                                      total_experiments)

print(flipped_heads)

flipped_heads.mean()

numpy.median(flipped_heads)

flipped_heads.sort()

print(flipped_heads)

len(flipped_heads)

print(flipped_heads[499])
print(flipped_heads[500])

import scipy.stats 

scipy.stats.mode(flipped_heads)[0][0]

print(scipy.stats.mode(flipped_heads))